### ISSUE TITLE
Add optional "pickletools.optimize" step to dump

### ISSUE THREAD

**Issue by SamuelBradley** [lucianopaz/compress_pickle#16]
Add optional "pickletools.optimize" step to dump prior to the compression. 
https://docs.python.org/3/library/pickletools.html#pickletools.optimize

This should squeeze some additional load performance and size reduction for minimal effort.

**Comment by lucianopaz** [comment]
Ah, I didn't know about `pickletools.optimize` this should be easy to add in.
