### ISSUE TITLE
bzip should be inferred from .bz2 extension

### ISSUE THREAD

**Issue by vtyw** [lucianopaz/compress_pickle#22]
The official extension for bzip2 is '.bz2', not '.bz', so ideally `load` and `dump` should be able to infer the format given a '.bz2' filename extension.

**Comment by lucianopaz** [comment]
Thanks @vtyw! I'll incorporate that extension. It shouldn't be too difficult, but I'm not sure if I'll be able to do so in the next week or so.

**Comment by lucianopaz** [comment]
Closed by #26
