### ISSUE TITLE
File ending with `.pkl.gz` is stored as `.pklgz`

### ISSUE THREAD

**Issue by LucaCappelletti94** [lucianopaz/compress_pickle#27]
Hello @lucianopaz,

Thank you for making this library!

I wanted to ask why, if the provided path is `.pkl.gz`, the files are stored as `.pklgz`.
This feels like an undesired default behaviour that may be, if necessary, enabled with a flag, as it breaks libraries that depend on the files to be stored as the given path requires.

Ciao e Grazie,
Luca

**Comment by lucianopaz** [comment]
Thanks from reporting @LucaCappelletti94. This is definitely a bug. I'll try to dig into it soon.

**Comment by lucianopaz** [comment]
Nevermind, in the end it was a dumb bug.
