### ISSUE TITLE
document the recognized extensions

### ISSUE THREAD

**Issue by jerabaul29** [lucianopaz/compress_pickle#31]
From the user manual https://lucianopaz.github.io/compress_pickle/html/ :

```
>>> fname2 = "gzip_compressed_data.gz"  # The compression is inferred from the extension
>>> dump(obj, fname2)
```

Can you document there which extensions are recognized? Which extensions can I use to automatically use lzma for example?

**Comment by lucianopaz** [comment]
You can find the list of registered extensions by calling:

```python
from compress_pickle.compressers.registry import get_registered_extensions

get_registered_extensions()
```

I'll explicitly write that down in the documentation. The information is in the API docs but it's harder to find.
