### ISSUE TITLE
JSON Support

### ISSUE THREAD

**Issue by eode** [lucianopaz/compress_pickle#39]
Would you be interested in JSON (and, for multiples, NDJSON/JSONLines) support for this module?  I know its name is "compress_pickle", but the option would be welcome for those who want compressed, serialized data but don't want the concomitant security risks of pickle.

Specifically, if this were implemented, would you accept a PR?

**Comment by lucianopaz** [comment]
Definitely! It's a great idea

**Comment by lucianopaz** [comment]
Closed by #40
